Services:
  DevOpsDB:
    build: ./database
    image: tp1-devopsdb
    env_file: ./database/.env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - net1
    restart: never #we would put a unless stopped here

  DevOpsBACK:
    build: ./backend
    image: tp1-devopsback
    env_file: ./backend/.env
    networks:
      - net1
      - net2
    depends_on:
      - DevOpsDB
    restart: on-failure:3
    

  DevOpsFRONT:
    build: ./frontend
    image: tp1-devopsfront
    ports:
      - "80:80"
    networks:
      - net2
      - net3
    depends_on:
      - DevOpsBACK
    restart: never
  

  DevOpsINTERFACE:
    build: ./interface
    image: tp1-devopsinterface
    networks:
      - net3
    depends_on:
      - DevOpsBACK
    restart: unless-stopped

networks:
  net1:
  net2:
  net3:

volumes:
  db-data:
