name: CI devops 2025 

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and test with Maven
        run: mvn clean verify
        working-directory: ./backend

      - name: SonarCloud analysis
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=NathanRCHD_Dev_Ops -Dsonar.organization=nathanrchd -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        working-directory: ./backend

  build-and-push-docker-image:
    needs: test-backend
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          tags: nathanrchd/tp1-devopsback:latest
          push: true

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          tags: nathanrchd/tp1-devopsfront:latest
          push: true

      - name: Build and push database image
        uses: docker/build-push-action@v6
        with:
          context: ./database
          tags: nathanrchd/tp1-devopsdb:latest
          push: true
